export { default as Home } from './home'
export { default as About } from './about'
export { default as Contact } from './contact'
export { default as SignUp } from './signup'
export { default as Login } from './login'